In [1]:
from models.models import Model
from mxnet import gpu, nd, cpu
import pickle
import os
from tqdm import trange

In [2]:
def read_pkl(path):
    return pickle.load(open(path,'rb'))

## 参数配置

In [3]:
model_param = {
    'emb_size':200,
    'hidden_size':200
}
vocab_path = 'data/vocab'
source_path = 'data/cnn_articles'
target_path = 'data/cnn_abstracts'
lda_path = 'data/cnn_head_lda'

In [4]:
# __init__(self, model_param, vocab_path, mode='train', vocab_tag_path=None, encoder_type='rnn', head_attention=False, deocder_cell='lstm', ctx=cpu(0))

In [5]:
model = Model(model_param, vocab_path, head_attention=True, decoder_cell='dlstm',ctx=cpu())

In [6]:
res = model.decode(source_path, lda_path, 'best.model')

100%|██████████| 1093/1093 [01:41<00:00, 10.79it/s]

decode done


In [7]:
abc = res.asscalar()

AttributeError: 'list' object has no attribute 'asscalar'

In [27]:
for i in res[117].astype(int).asnumpy():
    print(vocab.id2word(i), end=' ')

<start> <s> the is is the the of of of of of of of the </s> <s> <s> <s> <s> <s> <s> <s> <s> <s> </s> </s> </s> <stop> <stop> <stop> <stop> <stop> <stop> <stop> <stop> <stop> <stop> <stop> <stop> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> 

In [9]:
import pickle
pickle.dump(res, open('res.pkl','wb'))

In [17]:
from models.vocab import Vocab
vocab = Vocab(vocab_path)

In [6]:
x = nd.array([[1,2,3,4]])
y = nd.array([2,3])
lda = nd.array([[3,2]])
x.shape, y.shape, lda.shape
# data = [[x,y, lda]]

((1, 4), (2,), (1, 2))

In [7]:
headlines_path = '/home/xuyang/data/headline_lda'
articles_path = '/home/xuyang/data/articles/'
abstracts_path = '/home/xuyang/data/abstracts/'

headlines_files = os.listdir('/home/xuyang/data/headline_lda')


lda = nd.array([read_pkl(os.path.join(headlines_path,headlines_files[3]))])
x = nd.array([read_pkl(os.path.join(articles_path, headlines_files[3][:-4]+'story'))])
y = nd.array(read_pkl(os.path.join(abstracts_path, headlines_files[3][:-4]+'story')))
data = [[x,y,lda]]
# print(x.shape, y.shape, lda.shape)

_ = model.train_one_step(data)

loss= 12.207


In [8]:
for i in trange(20):
    _ = model.train_one_step(data, verbose=False)

100%|██████████| 20/20 [00:57<00:00,  2.88s/it]


In [20]:
model.train_one_step(data, verbose=True)

loss= 3.554



[[-5.1213155 -5.0762978 -4.9919744 ... -5.2387757 -5.3434753 -5.194275 ]
 [-6.6616373 -6.6720834 -6.474985  ... -6.6886625 -6.7228885 -6.5693426]
 [-7.0490904 -7.076274  -6.884171  ... -7.0131345 -7.0088725 -6.904545 ]
 ...
 [-7.7998133 -7.845614  -7.933001  ... -7.772173  -7.8246827 -7.9367924]
 [-8.169714  -8.180588  -8.15641   ... -7.947149  -8.093786  -8.225883 ]
 [-8.170695  -8.180966  -8.157208  ... -7.947079  -8.094528  -8.22617  ]]
<NDArray 70x200006 @cpu(0)>

In [7]:
from mxnet.gluon import rnn

In [9]:
lstm = rnn.LSTM(10)
lstm.initialize(ctx=gpu())

In [10]:
lstm

LSTM(None -> 10, TNC)

In [13]:
lstm.begin_state(batch_size=2)

[
 [[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
 <NDArray 1x2x10 @cpu(0)>, 
 [[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
 <NDArray 1x2x10 @cpu(0)>]